(function(){
    // banco de preguntas por materia
    const bank = {
        // 1er semestre: Álgebra (50 preguntas)
        algebra: [
            {q: '¿Cuánto vale x en: 2x + 4 = 10?', a: ['3','2','4','-3'], correct: 0},
            {q: 'Resuelve: 5x − 15 = 0', a: ['3','0','-3','5'], correct: 0},
            {q: 'Resuelve: 3x = 27', a: ['9','3','6','27'], correct: 0},
            {q: 'Resuelve: 10 − x = 4', a: ['6','-6','4','14'], correct: 0},
            {q: 'Resuelve: 4x + 2 = 14', a: ['3','2','4','6'], correct: 0},
            {q: 'Resuelve: 6x − 8 = 10', a: ['3','2','-3','4'], correct: 0},
            {q: 'Resuelve: 9x = 81', a: ['9','8','81','3'], correct: 0},
            {q: 'Resuelve: 2(x + 5) = 20', a: ['5','10','15','20'], correct: 0},
            {q: 'Resuelve: x/3 = 7', a: ['21','7','3','14'], correct: 0},
            {q: 'Resuelve: 5(x − 2) = 15', a: ['5','3','-5','10'], correct: 0},
            {q: 'Resuelve: 3x + 4 = 2x + 10', a: ['6','-6','2','4'], correct: 0},
            {q: 'Resuelve: 7x − 3 = 4x + 12', a: ['5','-5','3','4'], correct: 0},
            {q: 'Resuelve: 6 − 2x = x + 9', a: ['-1','1','3','0'], correct: 0},
            {q: 'Resuelve: 4(x + 1) = 3x + 10', a: ['6','5','4','-6'], correct: 0},
            {q: 'Resuelve: 8x − 5 = 3(2x + 1)', a: ['4','3','2','-4'], correct: 0},
            {q: 'Resuelve: 2x + 3 = 3x − 4', a: ['7','-7','1','-1'], correct: 0},
            {q: 'Resuelve: 10x + 2 = 8x + 12', a: ['5','2','-5','10'], correct: 0},
            {q: 'Resuelve: 9 − x = 2x + 3', a: ['2','-2','3','4'], correct: 0},
            {q: 'Resuelve: 12 − 4x = 2x', a: ['2','-2','4','6'], correct: 0},
            {q: 'Resuelve: 5 − (x − 3) = 10', a: ['-2','2','5','-5'], correct: 0},
            {q: '(x + 5)² = ?', a: ['x² + 10x + 25','x² + 5x + 25','x² + 25','x² + 10x'], correct: 0},
            {q: '(x − 3)(x − 3) =', a: ['x² − 6x + 9','x² − 3x + 9','x² − 9','x² + 6x + 9'], correct: 0},
            {q: '(x + 4)(x − 4) =', a: ['x² − 16','x² + 16','x² − 8x','x² + 0'], correct: 0},
            {q: '(2x + 3)(2x − 3) =', a: ['4x² − 9','4x² + 9','4x² − 6x','4x² + 6x'], correct: 0},
            {q: '(x + 1)(x + 2) =', a: ['x² + 3x + 2','x² + x + 2','x² + 2x + 1','x² + 4x + 2'], correct: 0},
            {q: '(3x − 2)(x + 4) =', a: ['3x² + 10x − 8','3x² + 12x − 8','3x² + 4x − 8','3x² + 8x − 8'], correct: 0},
            {q: '(x − 5)(x + 7) =', a: ['x² + 2x − 35','x² + 12x − 35','x² − 2x − 35','x² + 35'], correct: 0},
            {q: '(2x + 1)² =', a: ['4x² + 4x + 1','4x² + 1 + 2x','4x² + 2x + 1','4x² + 2x'], correct: 0},
            {q: '(x − 6)(x + 6) =', a: ['x² − 36','x² + 36','x² − 12x','x² + 6'], correct: 0},
            {q: '(4x − 1)(4x + 1) =', a: ['16x² − 1','16x² + 1','8x² − 1','16x² − 4'], correct: 0},
            {q: 'Factoriza: x² − 9', a: ['(x − 3)(x + 3)','(x − 9)(x + 1)','(x − 1)(x + 9)','(x − 3)²'], correct: 0},
            {q: 'Factoriza: x² + 7x + 10', a: ['(x + 5)(x + 2)','(x + 10)(x + 1)','(x + 2)(x + 5)','(x + 4)(x + 3)'], correct: 0},
            {q: 'Factoriza: x² − 5x + 6', a: ['(x − 2)(x − 3)','(x − 1)(x − 6)','(x − 3)(x − 2)','(x + 2)(x + 3)'], correct: 0},
            {q: 'Factoriza: 2x² + 8x', a: ['2x(x + 4)','2(x + 4)x','x(2x + 8)','2x(x + 8)'], correct: 0},
            {q: 'Factoriza: 3x² − 12', a: ['3(x − 2)(x + 2)','3(x² − 4)','(3x − 2)(x + 6)','3x(x − 4)'], correct: 0},
            {q: 'Factoriza: x² − x − 6', a: ['(x − 3)(x + 2)','(x + 3)(x − 2)','(x − 6)(x + 1)','(x + 6)(x − 1)'], correct: 0},
            {q: 'Factoriza: 4x² − 25', a: ['(2x − 5)(2x + 5)','(4x − 5)(x + 5)','(2x − 25)(2x + 1)','(4x − 25)(x + 1)'], correct: 0},
            {q: 'Factoriza: x² + 3x − 10', a: ['(x + 5)(x − 2)','(x + 2)(x − 5)','(x − 5)(x + 2)','(x + 10)(x − 1)'], correct: 0},
            {q: 'Factoriza: x² − 4x', a: ['x(x − 4)','(x − 2)(x − 2)','(x + 4)(x − 0)','(x − 1)(x − 3)'], correct: 0},
            {q: 'Factoriza: 5x² + 10x', a: ['5x(x + 2)','5(x + 2)x','x(5x + 10)','5x(x + 10)'], correct: 0},
            {q: 'Simplifica: 3x + 4x', a: ['7x','12x','1x','x7'], correct: 0},
            {q: 'Simplifica: 10x − 6x', a: ['4x','16x','-4x','6x'], correct: 0},
            {q: 'Simplifica: 2(x + 3) + x', a: ['3x + 6','2x + 3','x + 6','4x + 6'], correct: 0},
            {q: 'Simplifica: 5(x − 2) − 3x', a: ['2x − 10','2x + 10','-2x -10','2x - 6'], correct: 0},
            {q: 'Simplifica: (3x² + 2x) − (x² − x)', a: ['2x² + 3x','4x² + x','2x² + x','x² + 3x'], correct: 0},
            {q: 'Simplifica: 4x(2x + 1)', a: ['8x² + 4x','4x² + x','8x² + x','2x² + 4x'], correct: 0},
            {q: 'Simplifica: (x + 5) − (2x − 3)', a: ['-x + 8','x + 8','-x -8','-2x + 2'], correct: 0},
            {q: 'Simplifica: 6(x − 1) + 2x', a: ['8x − 6','6x − 6','8x + 6','4x − 6'], correct: 0},
            {q: 'Simplifica: (3x − 2x²) + (x² − x)', a: ['-x² + 2x','x² + x','-2x² + x','x - x²'], correct: 0},
            {q: 'Simplifica: 7x − 3(2x − 4)', a: ['x + 12','x - 12','-x + 12','x + 4'], correct: 0}
        ],

        // Inglés I (50 preguntas proporcionadas por el usuario)
        ingles1: [
            {q: 'What is the verb “to be” in the form of “yo”?', a: ['Am','Is','Are','Be'], correct: 0},
            {q: 'Complete: She ___ a student.', a: ['Is','Am','Are','Be'], correct: 0},
            {q: 'Complete: They ___ friends.', a: ['Are','Is','Am','Be'], correct: 0},
            {q: 'Complete: I ___ from Mexico.', a: ['Am','Is','Are','Be'], correct: 0},
            {q: 'Negative form: He is tall → He ___ tall.', a: ['Is not','Is','Are','Does not'], correct: 0},
            {q: 'Question: You are happy → ___ you happy?', a: ['Are','Is','Am','Do'], correct: 0},
            {q: 'Short answer: Are they here? → Yes, ___ ___.', a: ['They are','They aren\'t','Yes, they','They'], correct: 0},
            {q: 'Short answer: Is she your sister? → No, ___ ___.', a: ['She isn\'t','She is','No, she','She aren\'t'], correct: 0},
            {q: 'Complete: We ___ not tired.', a: ['Are','Is','Am','Do'], correct: 0},
            {q: 'Complete: My name ___ Carlos.', a: ['Is','Are','Am','Be'], correct: 0},
            {q: 'What is the third-person singular of “play”?', a: ['Plays','Play','Played','Playing'], correct: 0},
            {q: 'Complete: She ___ English every day. (study)', a: ['Studies','Study','Studys','Studied'], correct: 0},
            {q: 'Complete: They ___ soccer on weekends. (play)', a: ['Play','Plays','Played','Playing'], correct: 0},
            {q: 'Negative: He likes pizza → He ___ like pizza.', a: ['Doesn\'t','Don\'t','Isn\'t','Does'], correct: 0},
            {q: 'Negative: They work here → They ___ work here.', a: ['Don\'t','Doesn\'t','Isn\'t','Do'], correct: 0},
            {q: 'Question: ___ you speak English?', a: ['Do','Does','Are','Is'], correct: 0},
            {q: 'Question: ___ he live in Mexico?', a: ['Does','Do','Is','Are'], correct: 0},
            {q: 'Complete: The sun ___ in the east. (rise)', a: ['Rises','Rise','Rised','Is rising'], correct: 0},
            {q: 'Complete: My mom ___ dinner at 7 pm. (cook)', a: ['Cooks','Cook','Cooked','Is cooking'], correct: 0},
            {q: 'Correct the sentence: He don\'t like music.', a: ['He doesn\'t like music.','He not like music.','He didn\'t like music.','He no like music.'], correct: 0},
            {q: 'Choose the correct article: ___ apple', a: ['An','A','The','No article'], correct: 0},
            {q: 'Choose the correct article: ___ dog', a: ['A','An','The','No article'], correct: 0},
            {q: 'Choose: I have ___ umbrella.', a: ['An','A','The','No article'], correct: 0},
            {q: 'Choose: She is ___ best student.', a: ['The','A','An','No article'], correct: 0},
            {q: 'Choose: I want ___ new phone.', a: ['A','An','The','No article'], correct: 0},
            {q: 'Replace the noun: María = ___', a: ['She','He','They','It'], correct: 0},
            {q: 'Replace the noun: The dogs = ___', a: ['They','Them','He','It'], correct: 0},
            {q: 'Replace the noun: Juan and I = ___', a: ['We','Us','They','He'], correct: 0},
            {q: 'Replace the noun: The book = ___', a: ['It','They','He','She'], correct: 0},
            {q: 'Replace the noun: Carlos = ___', a: ['He','She','They','It'], correct: 0},
            {q: 'What does “Where?” ask for?', a: ['A place','A person','A reason','A time'], correct: 0},
            {q: 'What does “When?” ask for?', a: ['A time / date','A place','A person','A reason'], correct: 0},
            {q: 'What does “Who?” ask for?', a: ['A person','A place','A time','A reason'], correct: 0},
            {q: 'What does “Why?” ask for?', a: ['A reason','A place','A person','A time'], correct: 0},
            {q: 'What does “What?” ask for?', a: ['Information','A person','A place','A reason'], correct: 0},
            {q: 'Complete: ___ is your name?', a: ['What','When','Who','Where'], correct: 0},
            {q: 'Complete: ___ do you live?', a: ['Where','What','When','Who'], correct: 0},
            {q: 'Complete: ___ is the exam?', a: ['When','Where','Who','Why'], correct: 0},
            {q: 'Complete: ___ is your teacher?', a: ['Who','What','When','Where'], correct: 0},
            {q: 'Complete: ___ are you sad?', a: ['Why','When','Who','Where'], correct: 0},
            {q: 'Meaning of “house”?', a: ['Casa','Home','Lugar','Hogar'], correct: 0},
            {q: 'Meaning of “teacher”?', a: ['Maestro(a)','Profesor','Alumno','Estudiante'], correct: 0},
            {q: 'Meaning of “homework”?', a: ['Tarea','Casa','Trabajo','Deber'], correct: 0},
            {q: 'Meaning of “bookstore”?', a: ['Librería','Biblioteca','Tienda','Escuela'], correct: 0},
            {q: 'Meaning of “library”?', a: ['Biblioteca','Librería','Casa','Tienda'], correct: 0},
            {q: 'Opposite of “big”?', a: ['Small','Large','Huge','Tiny'], correct: 0},
            {q: 'Opposite of “hot”?', a: ['Cold','Warm','Cool','Boiling'], correct: 0},
            {q: 'Opposite of “early”?', a: ['Late','Soon','Ahead','Timely'], correct: 0},
            {q: 'Synonym of “happy”?', a: ['Glad','Sad','Angry','Tired'], correct: 0},
            {q: 'Synonym of “correct”?', a: ['Right','Wrong','Incorrect','False'], correct: 0}
        ],