(function(){
    // banco de preguntas por materia
    const bank = {
        // 1er semestre: Álgebra (50 preguntas)
        algebra: [
            {q: '¿Cuánto vale x en: 2x + 4 = 10?', a: ['3','2','4','-3'], correct: 0},
            {q: 'Resuelve: 5x − 15 = 0', a: ['3','0','-3','5'], correct: 0},
            {q: 'Resuelve: 3x = 27', a: ['9','3','6','27'], correct: 0},
            {q: 'Resuelve: 10 − x = 4', a: ['6','-6','4','14'], correct: 0},
            {q: 'Resuelve: 4x + 2 = 14', a: ['3','2','4','6'], correct: 0},
            {q: 'Resuelve: 6x − 8 = 10', a: ['3','2','-3','4'], correct: 0},
            {q: 'Resuelve: 9x = 81', a: ['9','8','81','3'], correct: 0},
            {q: 'Resuelve: 2(x + 5) = 20', a: ['5','10','15','20'], correct: 0},
            {q: 'Resuelve: x/3 = 7', a: ['21','7','3','14'], correct: 0},
            {q: 'Resuelve: 5(x − 2) = 15', a: ['5','3','-5','10'], correct: 0},
            {q: 'Resuelve: 3x + 4 = 2x + 10', a: ['6','-6','2','4'], correct: 0},
            {q: 'Resuelve: 7x − 3 = 4x + 12', a: ['5','-5','3','4'], correct: 0},
            {q: 'Resuelve: 6 − 2x = x + 9', a: ['-1','1','3','0'], correct: 0},
            {q: 'Resuelve: 4(x + 1) = 3x + 10', a: ['6','5','4','-6'], correct: 0},
            {q: 'Resuelve: 8x − 5 = 3(2x + 1)', a: ['4','3','2','-4'], correct: 0},
            {q: 'Resuelve: 2x + 3 = 3x − 4', a: ['7','-7','1','-1'], correct: 0},
            {q: 'Resuelve: 10x + 2 = 8x + 12', a: ['5','2','-5','10'], correct: 0},
            {q: 'Resuelve: 9 − x = 2x + 3', a: ['2','-2','3','4'], correct: 0},
            {q: 'Resuelve: 12 − 4x = 2x', a: ['2','-2','4','6'], correct: 0},
            {q: 'Resuelve: 5 − (x − 3) = 10', a: ['-2','2','5','-5'], correct: 0},
            {q: '(x + 5)² = ?', a: ['x² + 10x + 25','x² + 5x + 25','x² + 25','x² + 10x'], correct: 0},
            {q: '(x − 3)(x − 3) =', a: ['x² − 6x + 9','x² − 3x + 9','x² − 9','x² + 6x + 9'], correct: 0},
            {q: '(x + 4)(x − 4) =', a: ['x² − 16','x² + 16','x² − 8x','x² + 0'], correct: 0},
            {q: '(2x + 3)(2x − 3) =', a: ['4x² − 9','4x² + 9','4x² − 6x','4x² + 6x'], correct: 0},
            {q: '(x + 1)(x + 2) =', a: ['x² + 3x + 2','x² + x + 2','x² + 2x + 1','x² + 4x + 2'], correct: 0},
            {q: '(3x − 2)(x + 4) =', a: ['3x² + 10x − 8','3x² + 12x − 8','3x² + 4x − 8','3x² + 8x − 8'], correct: 0},
            {q: '(x − 5)(x + 7) =', a: ['x² + 2x − 35','x² + 12x − 35','x² − 2x − 35','x² + 35'], correct: 0},
            {q: '(2x + 1)² =', a: ['4x² + 4x + 1','4x² + 1 + 2x','4x² + 2x + 1','4x² + 2x'], correct: 0},
            {q: '(x − 6)(x + 6) =', a: ['x² − 36','x² + 36','x² − 12x','x² + 6'], correct: 0},
            {q: '(4x − 1)(4x + 1) =', a: ['16x² − 1','16x² + 1','8x² − 1','16x² − 4'], correct: 0},
            {q: 'Factoriza: x² − 9', a: ['(x − 3)(x + 3)','(x − 9)(x + 1)','(x − 1)(x + 9)','(x − 3)²'], correct: 0},
            {q: 'Factoriza: x² + 7x + 10', a: ['(x + 5)(x + 2)','(x + 10)(x + 1)','(x + 2)(x + 5)','(x + 4)(x + 3)'], correct: 0},
            {q: 'Factoriza: x² − 5x + 6', a: ['(x − 2)(x − 3)','(x − 1)(x − 6)','(x − 3)(x − 2)','(x + 2)(x + 3)'], correct: 0},
            {q: 'Factoriza: 2x² + 8x', a: ['2x(x + 4)','2(x + 4)x','x(2x + 8)','2x(x + 8)'], correct: 0},
            {q: 'Factoriza: 3x² − 12', a: ['3(x − 2)(x + 2)','3(x² − 4)','(3x − 2)(x + 6)','3x(x − 4)'], correct: 0},
            {q: 'Factoriza: x² − x − 6', a: ['(x − 3)(x + 2)','(x + 3)(x − 2)','(x − 6)(x + 1)','(x + 6)(x − 1)'], correct: 0},
            {q: 'Factoriza: 4x² − 25', a: ['(2x − 5)(2x + 5)','(4x − 5)(x + 5)','(2x − 25)(2x + 1)','(4x − 25)(x + 1)'], correct: 0},
            {q: 'Factoriza: x² + 3x − 10', a: ['(x + 5)(x − 2)','(x + 2)(x − 5)','(x − 5)(x + 2)','(x + 10)(x − 1)'], correct: 0},
            {q: 'Factoriza: x² − 4x', a: ['x(x − 4)','(x − 2)(x − 2)','(x + 4)(x − 0)','(x − 1)(x − 3)'], correct: 0},
            {q: 'Factoriza: 5x² + 10x', a: ['5x(x + 2)','5(x + 2)x','x(5x + 10)','5x(x + 10)'], correct: 0},
            {q: 'Simplifica: 3x + 4x', a: ['7x','12x','1x','x7'], correct: 0},
            {q: 'Simplifica: 10x − 6x', a: ['4x','16x','-4x','6x'], correct: 0},
            {q: 'Simplifica: 2(x + 3) + x', a: ['3x + 6','2x + 3','x + 6','4x + 6'], correct: 0},
            {q: 'Simplifica: 5(x − 2) − 3x', a: ['2x − 10','2x + 10','-2x -10','2x - 6'], correct: 0},
            {q: 'Simplifica: (3x² + 2x) − (x² − x)', a: ['2x² + 3x','4x² + x','2x² + x','x² + 3x'], correct: 0},
            {q: 'Simplifica: 4x(2x + 1)', a: ['8x² + 4x','4x² + x','8x² + x','2x² + 4x'], correct: 0},
            {q: 'Simplifica: (x + 5) − (2x − 3)', a: ['-x + 8','x + 8','-x -8','-2x + 2'], correct: 0},
            {q: 'Simplifica: 6(x − 1) + 2x', a: ['8x − 6','6x − 6','8x + 6','4x − 6'], correct: 0},
            {q: 'Simplifica: (3x − 2x²) + (x² − x)', a: ['-x² + 2x','x² + x','-2x² + x','x - x²'], correct: 0},
            {q: 'Simplifica: 7x − 3(2x − 4)', a: ['x + 12','x - 12','-x + 12','x + 4'], correct: 0}
        ],

        // Inglés I (50 preguntas proporcionadas por el usuario)
        ingles1: [
            {q: 'What is the verb “to be” in the form of “yo”?', a: ['Am','Is','Are','Be'], correct: 0},
            {q: 'Complete: She ___ a student.', a: ['Is','Am','Are','Be'], correct: 0},
            {q: 'Complete: They ___ friends.', a: ['Are','Is','Am','Be'], correct: 0},
            {q: 'Complete: I ___ from Mexico.', a: ['Am','Is','Are','Be'], correct: 0},
            {q: 'Negative form: He is tall → He ___ tall.', a: ['Is not','Is','Are','Does not'], correct: 0},
            {q: 'Question: You are happy → ___ you happy?', a: ['Are','Is','Am','Do'], correct: 0},
            {q: 'Short answer: Are they here? → Yes, ___ ___.', a: ['They are','They aren\'t','Yes, they','They'], correct: 0},
            {q: 'Short answer: Is she your sister? → No, ___ ___.', a: ['She isn\'t','She is','No, she','She aren\'t'], correct: 0},
            {q: 'Complete: We ___ not tired.', a: ['Are','Is','Am','Do'], correct: 0},
            {q: 'Complete: My name ___ Carlos.', a: ['Is','Are','Am','Be'], correct: 0},
            {q: 'What is the third-person singular of “play”?', a: ['Plays','Play','Played','Playing'], correct: 0},
            {q: 'Complete: She ___ English every day. (study)', a: ['Studies','Study','Studys','Studied'], correct: 0},
            {q: 'Complete: They ___ soccer on weekends. (play)', a: ['Play','Plays','Played','Playing'], correct: 0},
            {q: 'Negative: He likes pizza → He ___ like pizza.', a: ['Doesn\'t','Don\'t','Isn\'t','Does'], correct: 0},
            {q: 'Negative: They work here → They ___ work here.', a: ['Don\'t','Doesn\'t','Isn\'t','Do'], correct: 0},
            {q: 'Question: ___ you speak English?', a: ['Do','Does','Are','Is'], correct: 0},
            {q: 'Question: ___ he live in Mexico?', a: ['Does','Do','Is','Are'], correct: 0},
            {q: 'Complete: The sun ___ in the east. (rise)', a: ['Rises','Rise','Rised','Is rising'], correct: 0},
            {q: 'Complete: My mom ___ dinner at 7 pm. (cook)', a: ['Cooks','Cook','Cooked','Is cooking'], correct: 0},
            {q: 'Correct the sentence: He don\'t like music.', a: ['He doesn\'t like music.','He not like music.','He didn\'t like music.','He no like music.'], correct: 0},
            {q: 'Choose the correct article: ___ apple', a: ['An','A','The','No article'], correct: 0},
            {q: 'Choose the correct article: ___ dog', a: ['A','An','The','No article'], correct: 0},
            {q: 'Choose: I have ___ umbrella.', a: ['An','A','The','No article'], correct: 0},
            {q: 'Choose: She is ___ best student.', a: ['The','A','An','No article'], correct: 0},
            {q: 'Choose: I want ___ new phone.', a: ['A','An','The','No article'], correct: 0},
            {q: 'Replace the noun: María = ___', a: ['She','He','They','It'], correct: 0},
            {q: 'Replace the noun: The dogs = ___', a: ['They','Them','He','It'], correct: 0},
            {q: 'Replace the noun: Juan and I = ___', a: ['We','Us','They','He'], correct: 0},
            {q: 'Replace the noun: The book = ___', a: ['It','They','He','She'], correct: 0},
            {q: 'Replace the noun: Carlos = ___', a: ['He','She','They','It'], correct: 0},
            {q: 'What does “Where?” ask for?', a: ['A place','A person','A reason','A time'], correct: 0},
            {q: 'What does “When?” ask for?', a: ['A time / date','A place','A person','A reason'], correct: 0},
            {q: 'What does “Who?” ask for?', a: ['A person','A place','A time','A reason'], correct: 0},
            {q: 'What does “Why?” ask for?', a: ['A reason','A place','A person','A time'], correct: 0},
            {q: 'What does “What?” ask for?', a: ['Information','A person','A place','A reason'], correct: 0},
            {q: 'Complete: ___ is your name?', a: ['What','When','Who','Where'], correct: 0},
            {q: 'Complete: ___ do you live?', a: ['Where','What','When','Who'], correct: 0},
            {q: 'Complete: ___ is the exam?', a: ['When','Where','Who','Why'], correct: 0},
            {q: 'Complete: ___ is your teacher?', a: ['Who','What','When','Where'], correct: 0},
            {q: 'Complete: ___ are you sad?', a: ['Why','When','Who','Where'], correct: 0},
            {q: 'Meaning of “house”?', a: ['Casa','Home','Lugar','Hogar'], correct: 0},
            {q: 'Meaning of “teacher”?', a: ['Maestro(a)','Profesor','Alumno','Estudiante'], correct: 0},
            {q: 'Meaning of “homework”?', a: ['Tarea','Casa','Trabajo','Deber'], correct: 0},
            {q: 'Meaning of “bookstore”?', a: ['Librería','Biblioteca','Tienda','Escuela'], correct: 0},
            {q: 'Meaning of “library”?', a: ['Biblioteca','Librería','Casa','Tienda'], correct: 0},
            {q: 'Opposite of “big”?', a: ['Small','Large','Huge','Tiny'], correct: 0},
            {q: 'Opposite of “hot”?', a: ['Cold','Warm','Cool','Boiling'], correct: 0},
            {q: 'Opposite of “early”?', a: ['Late','Soon','Ahead','Timely'], correct: 0},
            {q: 'Synonym of “happy”?', a: ['Glad','Sad','Angry','Tired'], correct: 0},
            {q: 'Synonym of “correct”?', a: ['Right','Wrong','Incorrect','False'], correct: 0}
        ],
geometria_trigonometria: [
            {q: '¿Cuántos grados tiene un ángulo recto?', a: ['45°','60°','90°','180°'], correct: 2},
            {q: '¿Cuántos grados tiene un ángulo llano?', a: ['90°','180°','360°','270°'], correct: 1},
            {q: '¿Cuántos grados tiene un ángulo completo?', a: ['180°','90°','360°','270°'], correct: 2},
            {q: 'Ángulos que suman 90° se llaman…', a: ['Suplementarios','Complementarios','Opuestos','Adyacentes'], correct: 1},
            {q: 'Ángulos que suman 180° se llaman…', a: ['Complementarios','Suplementarios','Consecutivos','Congruentes'], correct: 1},
            {q: 'Ángulos opuestos por el vértice son…', a: ['Suplementarios','Complementarios','Iguales','Congruentes'], correct: 2},
            {q: 'Si dos ángulos son alternos internos, son…', a: ['Suplementarios','Iguales','Congruentes','Adyacentes'], correct: 2},
            {q: 'Si un ángulo mide 50°, su ángulo complementario mide…', a: ['35°','40°','50°','130°'], correct: 1},
            {q: 'Si un ángulo mide 120°, su ángulo suplementario mide…', a: ['60°','70°','90°','120°'], correct: 0},
            {q: 'La suma de ángulos internos de un triángulo es…', a: ['90°','360°','180°','270°'], correct: 2},
            {q: 'Triángulo con tres lados iguales:', a: ['Isósceles','Escaleno','Equilátero','Rectángulo'], correct: 2},
            {q: 'Triángulo con dos lados iguales:', a: ['Isósceles','Equilátero','Escaleno','Rectángulo'], correct: 0},
            {q: 'Triángulo con todos sus lados diferentes:', a: ['Equilátero','Isósceles','Escaleno','Rectángulo'], correct: 2},
            {q: 'Triángulo con un ángulo de 90°:', a: ['Equilátero','Isósceles','Rectángulo','Escaleno'], correct: 2},
            {q: 'Si un triángulo tiene lados 3, 4 y 5, es…', a: ['Isósceles','Equilátero','Rectángulo (pitagórico)','Escaleno'], correct: 2},
            {q: 'Suma de ángulos externos de cualquier polígono:', a: ['360°','180°','540°','720°'], correct: 0},
            {q: 'En un triángulo equilátero, cada ángulo mide…', a: ['60°','90°','45°','120°'], correct: 0},
            {q: 'Lado opuesto al ángulo recto en un triángulo rectángulo:', a: ['Cateto','Hipotenusa','Lado','Base'], correct: 1},
            {q: 'Si los catetos miden 6 y 8, la hipotenusa mide…', a: ['8','10','12','14'], correct: 1},
            {q: 'Si un ángulo agudo mide 35°, el otro mide como máximo…', a: ['55°','35°','90°','45°'], correct: 0},
            {q: 'Perímetro de un cuadrado de lado 5:', a: ['10','15','20','25'], correct: 2},
            {q: 'Área de un cuadrado de lado 5:', a: ['10','20','25','30'], correct: 2},
            {q: 'Área de un rectángulo de base 8 y altura 3:', a: ['11','24','40','22'], correct: 1},
            {q: 'Perímetro de un triángulo equilátero de lado 10:', a: ['10','20','30','40'], correct: 2},
            {q: 'Área de un triángulo de base 12 y altura 5:', a: ['17','30','60','25'], correct: 1},
            {q: 'Área de un círculo con radio 7:', a: ['153.94 (aprox)','49π','14π','98π'], correct: 1},
            {q: 'Circunferencia de un círculo con radio 10:', a: ['10π','20π','40π','200π'], correct: 1},
            {q: 'Área de un rombo con diagonales de 6 y 10:', a: ['16','30','60','10'], correct: 1},
            {q: 'Perímetro de un pentágono regular de lado 8:', a: ['32','36','40','48'], correct: 2},
            {q: 'Área de un trapecio con bases 10 y 6, y altura 4:', a: ['32','24','40','16'], correct: 0},
            {q: 'Sen 30°=', a: ['1/2','1','0','√3/2'], correct: 0},
            {q: 'Cos60°=', a: ['1/2','1','0','√3/2'], correct: 0},
            {q: 'Tan 45°=', a: ['0','1','√3','Indefinido'], correct: 1},
            {q: 'Sen 0°=', a: ['0','1','-1','Indefinido'], correct: 0},
            {q: 'Cos 0°=', a: ['0','1','-1','Indefinido'], correct: 1},
            {q: 'Sen 90°=', a: ['0','1','-1','Indefinido'], correct: 1},
            {q: 'Cos 90°=', a: ['0','1','-1','Indefinido'], correct: 0},
            {q: 'Tan 0°=', a: ['0','1','Indefinido','-1'], correct: 0},
            {q: 'Razón trigonométrica = lado opuesto / hipotenusa:', a: ['Coseno','Seno','Tangente','Cotangente'], correct: 1},
            {q: 'Razón trigonométrica = lado adyacente / hipotenusa:', a: ['Coseno','Seno','Tangente','Secante'], correct: 0},
            {q: 'Fórmula del Teorema de Pitágoras:', a: ['a + b = c','a^2 + b^2 = c^2','a^2 - b^2 = c','(a+b)^2 = c^2'], correct: 1},
            {q: 'Si los catetos miden 9 y 12, la hipotenusa mide…', a: ['13','15','18','21'], correct: 1},
            {q: 'Triángulo 30°-60°-90°, relación corta–hipotenusa:', a: ['Hipotenusa = cateto corto','Hipotenusa = 2 × cateto corto','Hipotenusa = cateto corto × √2','Hipotenusa = cateto corto / 2'], correct: 1},
            {q: 'Triángulo 45°-45°-90°, relación de lados:', a: ['Catetos iguales','Hipotenusa = cateto·√2','Catetos iguales, hipotenusa = cateto·√2','Ninguna'], correct: 2},
            {q: 'Cateto opuesto mide 8 y la hipotenusa 16:  =', a: ['1/4','1/2','2','8'], correct: 1},
            {q: 'Un polígono de 8 lados se llama…', a: ['Octágono','Heptágono','Decágono','Hexágono'], correct: 0},
            {q: 'Un polígono de 10 lados se llama…', a: ['Decágono','Hexágono','Octágono','Heptágono'], correct: 0},
            {q: 'Suma de ángulos internos de un cuadrado:', a: ['180°','90°','360°','270°'], correct: 2},
            {q: 'Suma de ángulos internos de un pentágono:', a: ['360°','540°','720°','900°'], correct: 1},
            {q: 'Suma de ángulos internos de un hexágono:', a: ['540°','720°','900°','1080°'], correct: 1}
        ],
        historia_mexico: [
            {q: 'Presidente que impulsó la industrialización por sustitución de importaciones (ISI):', a: ['Manuel Ávila Camacho','Miguel Alemán Valdés','Lázaro Cárdenas','Gustavo Díaz Ordaz'], correct: 0},
            {q: 'Presidente conocido por el “Desarrollo Estabilizador”:', a: ['Adolfo Ruiz Cortines','Miguel de la Madrid','Carlos Salinas','Vicente Fox'], correct: 0},
            {q: 'Periodo económico con crecimiento alto y estabilidad de precios (1954–1970):', a: ['La Depresión','El Milagro Mexicano','La Reconstrucción','La Estabilidad'], correct: 1},
            {q: 'Presidente que nacionalizó la industria eléctrica:', a: ['Adolfo López Mateos','Lázaro Cárdenas','Enrique Peña Nieto','Carlos Salinas'], correct: 0},
            {q: 'Acontecimiento estudiantil clave de 1968:', a: ['Matanza de Tlatelolco','Movimiento Zapatista','Reforma Universitaria','Toma del Zócalo'], correct: 0},
            {q: 'Presidente en el poder durante el movimiento del 68:', a: ['Gustavo Díaz Ordaz','Luis Echeverría','Adolfo López Mateos','Miguel Alemán'], correct: 0},
            {q: 'Presidente durante los Juegos Olímpicos de 1968:', a: ['Gustavo Díaz Ordaz','Luis Echeverría','Adolfo Ruiz Cortines','Vicente Fox'], correct: 0},
            {q: 'Política económica del desarrollo estabilizador se basó en…', a: ['Apertura total','Control de inflación y crecimiento industrial','Autarquía','Déficit fiscal elevado'], correct: 1},
            {q: 'Objetivo principal del desarrollo estabilizador:', a: ['Aumentar la inflación','Estabilidad económica sin inflación','Reducir la industria','Desindustrializar'], correct: 1},
            {q: 'Presidente que impulsó el crecimiento industrial y construyó Ciudad Universitaria:', a: ['Miguel Alemán Valdés','Lázaro Cárdenas','Carlos Salinas','Adolfo López Mateos'], correct: 0},
            {q: 'Presidente que inició la fase conocida como Desarrollo Compartido:', a: ['Luis Echeverría Álvarez','Miguel de la Madrid','José López Portillo','Vicente Fox'], correct: 0},
            {q: 'Presidente que nacionalizó la banca en 1982:', a: ['José López Portillo','Carlos Salinas','Miguel de la Madrid','Enrique Peña Nieto'], correct: 0},
            {q: 'Principal causa de la crisis de 1982:', a: ['Hiperinflación interna','Endeudamiento externo y caída del petróleo','Aumento de inversiones','Superávit comercial'], correct: 1},
            {q: 'Presidente que impulsó la apertura económica y privatizaciones:', a: ['Miguel de la Madrid','Luis Echeverría','Adolfo López Mateos','Gustavo Díaz Ordaz'], correct: 0},
            {q: 'Presidente que firmó el TLCAN (NAFTA):', a: ['Carlos Salinas de Gortari','Vicente Fox','Enrique Peña Nieto','Felipe Calderón'], correct: 0},
            {q: 'Año en que entró en vigor el TLCAN:', a: ['1992','1994','1996','2000'], correct: 1},
            {q: 'Movimiento indígena que surgió en Chiapas en 1994:', a: ['EZLN','PRI','PAN','PRD'], correct: 0},
            {q: 'Candidato presidencial asesinado en 1994:', a: ['Luis Donaldo Colosio','Carlos Salinas','Diego Fernández','Andrés Manuel López Obrador'], correct: 0},
            {q: 'Crisis económica del fin de 1994–1995 se conoce como…', a: ['Efecto Tequila','Gran Depresión','Crisis del 82','Bolsa Mexicana'], correct: 0},
            {q: 'Primer presidente del PAN en México:', a: ['Vicente Fox Quesada','Felipe Calderón','Carlos Salinas','Andrés Manuel López Obrador'], correct: 0},
            {q: 'Presidente en México durante 2000–2006:', a: ['Vicente Fox','Felipe Calderón','Enrique Peña Nieto','Carlos Salinas'], correct: 0},
            {q: 'Presidente en México durante 2006–2012:', a: ['Felipe Calderón','Enrique Peña Nieto','Vicente Fox','Andrés Manuel López Obrador'], correct: 0},
            {q: 'Política más conocida del sexenio de Calderón:', a: ['Reforma educativa','Guerra contra el narcotráfico','Nacionalización','Apertura comercial'], correct: 1},
            {q: 'Presidente de México en 2012–2018:', a: ['Enrique Peña Nieto','Felipe Calderón','Vicente Fox','Andrés Manuel López Obrador'], correct: 0},
            {q: 'Reforma educativa, energética y fiscal forman parte de…', a: ['Pacto por México','Plan Nacional','Acuerdo Fiscal','Ninguna'], correct: 0},
            {q: 'Presidente de México desde 2018:', a: ['Enrique Peña Nieto','Andrés Manuel López Obrador','Vicente Fox','Felipe Calderón'], correct: 1},
            {q: 'Programa social emblemático del actual gobierno:', a: ['Jóvenes Construyendo el Futuro','Progresa','Oportunidades','Seguro Popular'], correct: 0},
            {q: 'Proyecto ferroviario del sureste iniciado en 2019:', a: ['Tren Maya','Tren Transversal','Tren Rápido','Tren del Norte'], correct: 0},
            {q: 'Nueva aerolínea del gobierno mexicano (2023):', a: ['Mexicana de Aviación','Aeroméxico','Volaris','Interjet'], correct: 0},
            {q: 'Nuevo aeropuerto construido en 2022:', a: ['Aeropuerto Internacional Felipe Ángeles (AIFA)','NAIM','Aeropuerto Benito Juárez','Aeropuerto del Pacífico'], correct: 0},
            {q: 'La película mexicana ganadora del Óscar a Mejor Director en 2014 (Cuarón):', a: ['Roma','Gravity','Amores Perros','El Laberinto del Fauno'], correct: 1},
            {q: 'Movimiento universitario de 2012 contra Televisa:', a: ['#YoSoy132','Movimiento del 68','#NoalINAI','Movimiento Estudiantil'], correct: 0},
            {q: 'Evento cultural masivo que celebra el libro en Guadalajara:', a: ['FIL','Feria del Libro de México','Feria del Cine','Festival del Libro de Oaxaca'], correct: 0},
            {q: 'Institución responsable del patrimonio arqueológico:', a: ['CONACULTA','INE','INAH','SEP'], correct: 2},
            {q: 'Declaración emblemática del patrimonio cultural mexicano por la UNESCO:', a: ['La comida mexicana tradicional','El mariachi','La pintura mural','El cine mexicano'], correct: 0},
            {q: 'Celebración reconocida mundialmente como símbolo de México:', a: ['Navidad','Día de Muertos','Independencia','Revolución'], correct: 1},
            {q: 'Muralistas mexicanos más importantes:', a: ['Frida Kahlo, Rufino Tamayo','Diego Rivera, José Clemente Orozco, David Alfaro Siqueiros','Octavio Paz, Juan Rulfo','Carlos Fuentes, Elena Poniatowska'], correct: 1},
            {q: 'Ciudad conocida por el Festival Internacional Cervantino:', a: ['Guadalajara','Guanajuato','Monterrey','Puebla'], correct: 1},
            {q: 'Premio Nobel de Literatura mexicano:', a: ['Carlos Fuentes','Juan Rulfo','Octavio Paz','Laura Esquivel'], correct: 2},
            {q: 'Obra literaria famosa de Juan Rulfo:', a: ['Pedro Páramo','La región más transparente','El laberinto de la soledad','Como agua para chocolate'], correct: 0},
            {q: 'Institución autónoma encargada de controlar la inflación:', a: ['Banco de México','Secretaría de Hacienda','Banamex','Cámara de Diputados'], correct: 0},
            {q: 'Indicador económico que mide el crecimiento del país:', a: ['IPC','Tasa de interés','PIB','Inflación'], correct: 2},
            {q: 'Proceso mediante el cual el PRI perdió la hegemonía presidencial:', a: ['Golpe de Estado','Alternancia en el 2000','Revolución Mexicana','Crisis del 82'], correct: 1},
            {q: 'Organismo encargado de elecciones en México:', a: ['INE (antes IFE)','Tribunal Electoral','Cámara de Diputados','Corte Suprema'], correct: 0},
            {q: 'Periodo de un presidente en México:', a: ['4 años','5 años','6 años (sexenio)','8 años'], correct: 2},
            {q: 'Documento que establece las leyes supremas del país:', a: ['Carta Magna 1810','Constitución de 1917','Código Civil','Declaración de Independencia'], correct: 1},
            {q: 'Sistema político que tuvo dominio hegemónico por más de 70 años:', a: ['PAN','PRI','PRD','MORENA'], correct: 1},
            {q: 'Tratado comercial que reemplazó al TLCAN en 2020:', a: ['TLCAN II','T-MEC (USMCA)','Pacto del Pacífico','Tratado del Siglo'], correct: 1},
            {q: 'Cámara del Congreso encargada de aprobar el presupuesto:', a: ['Senado','Cámara de Diputados','Corte Suprema','Tribunal Fiscal'], correct: 1},
            {q: 'Ciudad donde se ubica la sede del gobierno federal:', a: ['Guadalajara','Ciudad de México','Monterrey','Puebla'], correct: 1}
        ],